-- Seed ~50 activity_log rows spread across event types and actors.
-- occurred_at values are recent so they land in the default partition.

INSERT INTO events.activity_log (occurred_at, actor_id, organization_id, event_type, payload)
VALUES
  (NOW() - INTERVAL '29 days', 1, 1, 'user.login',          '{"ip": "192.168.1.1",  "device": "web"}'),
  (NOW() - INTERVAL '29 days', 2, 1, 'user.login',          '{"ip": "10.0.0.5",     "device": "mobile"}'),
  (NOW() - INTERVAL '28 days', 1, 1, 'project.created',     '{"project_id": 1,      "name": "Billing API"}'),
  (NOW() - INTERVAL '28 days', 2, 1, 'project.created',     '{"project_id": 2,      "name": "Analytics Dashboard"}'),
  (NOW() - INTERVAL '27 days', 3, 1, 'project.created',     '{"project_id": 3,      "name": "Auth Service"}'),
  (NOW() - INTERVAL '27 days', 2, 2, 'project.created',     '{"project_id": 4,      "name": "Design System"}'),
  (NOW() - INTERVAL '26 days', 4, 2, 'project.created',     '{"project_id": 5,      "name": "Client Portal"}'),
  (NOW() - INTERVAL '26 days', 1, 1, 'task.created',        '{"task_id": 1,         "title": "Setup CI/CD"}'),
  (NOW() - INTERVAL '25 days', 2, 1, 'task.created',        '{"task_id": 2,         "title": "Write API docs"}'),
  (NOW() - INTERVAL '25 days', 3, 1, 'task.created',        '{"task_id": 3,         "title": "JWT implementation"}'),
  (NOW() - INTERVAL '24 days', 1, 1, 'task.status_changed', '{"task_id": 1,         "from": "todo",        "to": "in_progress"}'),
  (NOW() - INTERVAL '24 days', 2, 1, 'task.status_changed', '{"task_id": 2,         "from": "todo",        "to": "in_progress"}'),
  (NOW() - INTERVAL '23 days', 5, 2, 'user.login',          '{"ip": "203.0.113.10", "device": "web"}'),
  (NOW() - INTERVAL '23 days', 1, 1, 'invitation.sent',     '{"email": "new@teamsync.dev", "org_id": 1}'),
  (NOW() - INTERVAL '22 days', 3, 1, 'task.status_changed', '{"task_id": 3,         "from": "todo",        "to": "in_progress"}'),
  (NOW() - INTERVAL '22 days', 2, 2, 'task.created',        '{"task_id": 4,         "title": "Component library v2"}'),
  (NOW() - INTERVAL '21 days', 4, 2, 'user.login',          '{"ip": "198.51.100.1", "device": "mobile"}'),
  (NOW() - INTERVAL '21 days', 1, 1, 'task.status_changed', '{"task_id": 1,         "from": "in_progress", "to": "done"}'),
  (NOW() - INTERVAL '20 days', 2, 1, 'project.updated',     '{"project_id": 2,      "field": "description"}'),
  (NOW() - INTERVAL '20 days', 5, 2, 'task.created',        '{"task_id": 5,         "title": "Client onboarding flow"}'),
  (NOW() - INTERVAL '19 days', 1, 1, 'user.login',          '{"ip": "192.168.1.1",  "device": "web"}'),
  (NOW() - INTERVAL '19 days', 3, 1, 'invitation.sent',     '{"email": "dev@partner.io", "org_id": 1}'),
  (NOW() - INTERVAL '18 days', 2, 1, 'task.status_changed', '{"task_id": 2,         "from": "in_progress", "to": "done"}'),
  (NOW() - INTERVAL '18 days', 4, 2, 'project.updated',     '{"project_id": 5,      "field": "status"}'),
  (NOW() - INTERVAL '17 days', 5, 2, 'task.status_changed', '{"task_id": 5,         "from": "todo",        "to": "in_progress"}'),
  (NOW() - INTERVAL '17 days', 1, 1, 'task.created',        '{"task_id": 6,         "title": "Rate limiting middleware"}'),
  (NOW() - INTERVAL '16 days', 2, 1, 'task.created',        '{"task_id": 7,         "title": "Dashboard charts"}'),
  (NOW() - INTERVAL '16 days', 3, 1, 'task.status_changed', '{"task_id": 3,         "from": "in_progress", "to": "done"}'),
  (NOW() - INTERVAL '15 days', 1, 1, 'user.login',          '{"ip": "192.168.1.2",  "device": "web"}'),
  (NOW() - INTERVAL '15 days', 5, 2, 'user.login',          '{"ip": "203.0.113.10", "device": "desktop"}'),
  (NOW() - INTERVAL '14 days', 2, 2, 'task.status_changed', '{"task_id": 4,         "from": "todo",        "to": "in_progress"}'),
  (NOW() - INTERVAL '14 days', 1, 1, 'invitation.accepted', '{"email": "new@teamsync.dev", "org_id": 1}'),
  (NOW() - INTERVAL '13 days', 4, 2, 'task.status_changed', '{"task_id": 5,         "from": "in_progress", "to": "done"}'),
  (NOW() - INTERVAL '13 days', 3, 1, 'task.created',        '{"task_id": 8,         "title": "Token refresh logic"}'),
  (NOW() - INTERVAL '12 days', 1, 1, 'task.status_changed', '{"task_id": 6,         "from": "todo",        "to": "in_progress"}'),
  (NOW() - INTERVAL '12 days', 2, 1, 'project.updated',     '{"project_id": 1,      "field": "metadata"}'),
  (NOW() - INTERVAL '11 days', 5, 2, 'task.created',        '{"task_id": 9,         "title": "PDF export feature"}'),
  (NOW() - INTERVAL '11 days', 3, 1, 'user.login',          '{"ip": "10.0.0.7",     "device": "web"}'),
  (NOW() - INTERVAL '10 days', 1, 1, 'task.status_changed', '{"task_id": 6,         "from": "in_progress", "to": "done"}'),
  (NOW() - INTERVAL '10 days', 2, 1, 'task.status_changed', '{"task_id": 7,         "from": "todo",        "to": "in_progress"}'),
  (NOW() -  INTERVAL '9 days', 4, 2, 'user.login',          '{"ip": "198.51.100.2", "device": "mobile"}'),
  (NOW() -  INTERVAL '9 days', 1, 1, 'invitation.sent',     '{"email": "qa@teamsync.dev", "org_id": 1}'),
  (NOW() -  INTERVAL '8 days', 5, 2, 'task.status_changed', '{"task_id": 9,         "from": "todo",        "to": "in_progress"}'),
  (NOW() -  INTERVAL '8 days', 3, 1, 'task.status_changed', '{"task_id": 8,         "from": "todo",        "to": "in_progress"}'),
  (NOW() -  INTERVAL '7 days', 2, 1, 'task.status_changed', '{"task_id": 7,         "from": "in_progress", "to": "done"}'),
  (NOW() -  INTERVAL '7 days', 1, 1, 'project.updated',     '{"project_id": 3,      "field": "description"}'),
  (NOW() -  INTERVAL '5 days', 4, 2, 'task.status_changed', '{"task_id": 4,         "from": "in_progress", "to": "done"}'),
  (NOW() -  INTERVAL '5 days', 5, 2, 'task.status_changed', '{"task_id": 9,         "from": "in_progress", "to": "done"}'),
  (NOW() -  INTERVAL '3 days', 3, 1, 'task.status_changed', '{"task_id": 8,         "from": "in_progress", "to": "done"}'),
  (NOW() -  INTERVAL '2 days', 1, 1, 'user.login',          '{"ip": "192.168.1.1",  "device": "web"}'),
  (NOW() -  INTERVAL '1 day',  2, 1, 'user.login',          '{"ip": "10.0.0.5",     "device": "mobile"}');
